### ISSUE TITLE
[I am confused which is im-x86-trident-ub12 platform. Anyone can help me??]

### ISSUE THREAD

**Issue by PattinsonNguyen** [Broadcom-Switch/OpenNSL#1]
Hi everyone.

I have downloaded the OpenNSL zip package and I try to run the Makefile in folder: /OpenNSL-master/examples. However, I am confused which is "im-x86-trident-ub12 platform"? Is it exactly a Server PC which control the Switch as like the figure below or another board platform?

Thanks everyone for help!
![vidu1](https://cloud.githubusercontent.com/assets/13861413/9710905/3579e4a8-5569-11e5-82a7-bd21041034a5.png)

**Comment by simonknee** [comment]
The im-x86-trident-ub12 platform is the switch itself.  It is an Interface Masters switch with an x86 CPU running Ubuntu and using Trident switching silicon from Broadcom.  It is not the server in the above diagram.  See http://www.interfacemasters.com/products/switches/niagara-2948-12xlm-ocp-product-family.html.

Hope that helps.

**Comment by PattinsonNguyen** [comment]
As you mentioned that the Interface Masters switch with an x86 CPU running Ubuntu, so I consider why I cannot load the modules: linux-kernel-bde.ko and linux-user-bde.ko in folder /bin/im-x86-trident-ub12 into my Linux kernel version 3.19.0-26-generic with x86-64 CPU running Ubuntu 14.04.3. Are there any differences? because as I known x86-64 CPU can run x86 applications.

**Comment by simonknee** [comment]
The "ub12" in the platform means it was the Ubuntu 12.04 LTS.  As you say, if you match the kernel version then the modules should start to load on a regular server platform but then fail since they cannot find any Broadcom silicon.

**Comment by PattinsonNguyen** [comment]
So, can I ask the last silly question: the C code for module is private? And inside that code, it is required to look for the switching chip to load these modules successfully?

**Comment by simonknee** [comment]
These are not silly questions at all!  You are correct, currently the C code for the module is private.  That module is looking for the switching chip on the PCI bus, and will not do anything if it cannot find it.
