### ISSUE TITLE
OFDPA APIs in OpneNSL v3.3.0.2

### ISSUE THREAD

**Issue by evanjack2002** [Broadcom-Switch/OpenNSL#10]
Hi Sirs,

I use these OFDPA APIs in OpenNSL v3.3.02 on OpenSwitch project and use this example "http://www.openswitch.net/documents/user/ofdpa_hybrid_functionality_guide" to verify the Openflow functions.
The ofdpaFlowAdd() can add the flows and ofdpaGroupAdd() can add the groups, but the traffic can't work.

Does these OFDPA APIs work in OpenNSL v3.3.02?

Thanks.
Best regards,
Evan

**Comment by simonknee** [comment]
Hi Tim,

These APIs are present in OpenNSL v3.3.0.2 but they are being deprecated and have not been tested.  The reason is that these APIs were added for the OpenSwitch v1 project (AKA OPS), and since that is no longer moving forward (replaced by OpenSwitch v2, AKA OPX) we are removing them from OpenNSL.

If you do want to use these APIs in 3.3.0.2, with the understanding they are not tested, then you need to add a call to ofdpaInit() directly after opennsl_driver_init().  This is definitely a reason why calling ofdpaFlowAdd() is not doing anything for you.

Simon.

**Comment by simonknee** [comment]
Sorry, I mean Evan not Tim!

**Comment by evanjack2002** [comment]
Hi Simon,

Thanks for your reply.
I knew the ofdpaInit() issue and had added on my OPS code. The ofdpaFlowAdd() and ofdpaGroupAdd() can work on my OPS code and I can see the L2 entries on the chip.

root@switch:~# ovs-appctl plugin/debug drivsh 'l2 show'
mac=00:00:00:00:00:44 vlan=28674 GPORT=0x80000004 port=0x80000004(vxlan) Static
mac=00:00:00:00:00:33 vlan=28673 GPORT=0x80000002 port=0x80000002(vxlan) Static
mac=00:00:00:00:00:11 vlan=28673 GPORT=0x80000001 port=0x80000001(vxlan) Static
mac=00:00:00:00:00:22 vlan=28674 GPORT=0x80000003 port=0x80000003(vxlan) Static

But my question is the traffic can't work. 
I send the traffic on switch1 with "src_mac=00:00:00:00:00:11, dst_mac=00:00:00:00:00:33, vlan_tag=100" to port 1, but this traffic can't go out on port 3.

Best regards,
Evan

**Comment by simonknee** [comment]
You are ahead of me then!

Would it be possible to try the same on OpenNSL 3.1.0.17?  That was the last version of OpenNSL where the OF-DPA APIs were validated with OPS.  OPS/HPE never really moved forward to 3.2 or 3.3.

Simon.

**Comment by evanjack2002** [comment]
The OpenNSL 3.1.0.17 doesn't include the OF-DPA driver API's. I check the OpenNSL release note the first release OF-DPA APIs are on 3.2.0.1.

It means no one know these OF-DPA APIs can work on OpenNSL?

Thanks.
Evan

**Comment by simonknee** [comment]
Yes, my mistake again Evan.  OpenNSL 3.2.0.1 was the first release with OF-DPA support, and it that release train it was fully tested.  This was also the release train that was used by HPE to integrate into OPS.  Could you try your tests with OpenNSL 3.2.0.5?

Simon.

**Comment by evanjack2002** [comment]
Sorry, I don't have OpenNSL 3.2.0.5, only have OpenNSL 3.2.1.5 and 3.3.0.2. I check the OF-DPA code between two version codes. there is no difference on OF-DPA APIs.

As you say, the OpenNSL 3.2.01 was fully tested. Does it verify the OF-DPA APIs?

Evan

**Comment by simonknee** [comment]
Are you using the ODP version of OpenNSL Evan?  If so then let me know who you work for and I can look up your software license agreement.  You can email me at simon.knee at broadcom.com.

Yes, OpenNSL 3.2.0.x was fully tested including OF-DPA (for use in OPS).

**Comment by evanjack2002** [comment]
Yes, we are using the ODP version.
Please check your mail server, thanks.

Evan

**Comment by simonknee** [comment]
Got your email Even, just replied.
