### ISSUE TITLE
KNET doesn't work on AS5712-54x

### ISSUE THREAD

**Issue by hydratim** [Broadcom-Switch/OpenNSL#11]
I've been trying to get KNET to work on Accton AS5712 for about a week to no avail.
TX from KNET interface to real network works, RX packets seem to reach the ASIC, but doesn't get forwarded to the knet interface which registers:
```
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0                    
              TX packets:16 errors:0 dropped:0 overruns:0 carrier:0                 
              collisions:0 txqueuelen:1000                                          
              RX bytes:0 (0.0 B)  TX bytes:1360 (1.3 KiB) 
```

It looks to me like it's an issue with the kernel module.

```
Linux localhost 3.16.39-OpenNetworkLinux #5 SMP Fri Feb 24 12:57:12 CET 2017 x86_64 GNU/Linux
```

Any ideas?

**Comment by simonknee** [comment]
Are you using the provided AS5712 binaries on GitHub with the example_knet application?

**Comment by hydratim** [comment]
No they don't work with my running kernel (or the kernel from the latest build on the ONL site), but I think I've found the issue, I'm rebuilding the kernel and the OPENNSL modules again and I'll report back here.

**Comment by hydratim** [comment]
Think I might have found it, it's a Kernel 2.x vs 3.x difference, they removed last_rx from the net_device header back in 2016, instead we are expected to replace writes with `netif_trans_update(dev)` and reads with `x = dev_trans_start(dev)`
The following substitution should fix it, but it's late now so I'll validate the fix tomorrow when I have access to my test bench at work.
```
bcm-knet.c - Line 4025:
    //dev->last_rx = jiffies;
    netif_trans_update(dev)
```

In my previous build I must have mistakenly commented it out (or something silly like that) with the intention of fixing it later.

I'll update this thread tomorrow if the fix worked. Perhaps someone could independently verify if this change is backwards compatible with earlier kernels (for example 2.6) and then I'll submit a pull request. otherwise I propose a kernel-3.x branch is maintained separately from the master branch.

**Comment by hydratim** [comment]
Turns out that was in the tx section and doesn't fix my rx problem (as it happens it doesn't seem to do anything).

**Comment by simonknee** [comment]
Can you try using the unmodified libopennsl and kernel drivers from the as5712 bin directory?  These were verified to work before the release, so unless we missed some basic KNET testing they should work for you too.  If they do not then here are some additional debug commands to try and figure out what is going on - you probably know most of them anyway but including them here for completeness.

Print KNET interface and filters:
BCM.0> knetctrl netif show
BCM.0> knetctrl filter show

Print KNET statistics:
BCM.0> shell
bash-3.1# cat /proc/bcm/knet/dstats 
bash-3.1# cat /proc/bcm/knet/stats
Print KNET DMA informations:
bash-3.1# cat /proc/bcm/knet/dma

Print KNET rate informations:
bash-3.1# cat /proc/bcm/knet/rate

Enable/disable KNET debugging print:
bash-3.1# echo debug=0xffff > /proc/bcm/knet/debug
bash-3.1# cat /proc/bcm/knet/debug
bash-3.1# echo debug=0 > /proc/bcm/knet/debug
bash-3.1# cat /proc/bcm/knet/debug

**Comment by hydratim** [comment]
I'll find a matching kernel on Monday, I'm fairly certain it's just conflicts between the latest longterm kernel and the driver, but I first need to get something running before I start the serious kernel hacking.

I presume everything was built on a specific release of ONL, if so do you know which release?

**Comment by hydratim** [comment]
I haven't been able to find a matching OS <-> OpenNSL pair in all ONL releases. Any idea where I can get a copy of the OS you built the modules & library for?

**Comment by simonknee** [comment]
I am currently checking with the dev team, but I am pretty sure ONL was not the distribution that we used.  I will get back to you.

**Comment by hydratim** [comment]
Thanks Simon

**Comment by hydratim** [comment]
also my broadcom diag doesn't have any knet options, where can I get one that does?

**Comment by hydratim** [comment]
```
Exiting the application.

User Menu: Select one of the following options
1. Create KNET interface
2. Delete KNET interface
3. Display KNET interface database
9. Launch diagnostic shell
0. Quit the application.
1

Enter port number: 
1

Enter knet interface name: swp1

Enter IP address in dotted decimal format: 172.16.0.1

Enter IP netmask in dotted decimal format: 24
Created Interface ID 1 for interface name "swp1" 
Created Filter ID 1 for interface name "swp1" 
Created Linux interface "swp1" successfully.
SIOCSIFNETMASK: Invalid argument
Configured interface "swp1" with IP: 172.16.0.1 Netmask: 24

User Menu: Select one of the following options
1. Create KNET interface
2. Delete KNET interface
3. Display KNET interface database
9. Launch diagnostic shell
0. Quit the application.
3
Number of KNET interfaces present: 1

Port: 1 Interface Name: swp1 netifID: 1 filterID: 1

User Menu: Select one of the following options
1. Create KNET interface
2. Delete KNET interface
3. Display KNET interface database
9. Launch diagnostic shell
0. Quit the application.
9

Enter 'quit' to exit the application.
drivshell>ifconfig
Unknown command: ifconfig

command "ifconfig" failed.  rc = -3.

Failed to execute the diagnostic command. Error: Invalid unit.
drivshell>shell
root@Edge1-A:/home/tim/OpenNSL/examples# ifconfig
eth0      Link encap:Ethernet  HWaddr 80:1f:02:d6:3b:2b  
          inet addr:10.1.10.2  Bcast:10.1.255.255  Mask:255.255.0.0
          inet6 addr: fe80::821f:2ff:fed6:3b2b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:142175 errors:0 dropped:0 overruns:0 frame:0
          TX packets:54736 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:157959444 (157.9 MB)  TX bytes:4963728 (4.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:31 errors:0 dropped:0 overruns:0 frame:0
          TX packets:31 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:3472 (3.4 KB)  TX bytes:3472 (3.4 KB)

swp1      Link encap:Ethernet  HWaddr 02:10:18:00:00:01  
          inet addr:172.16.0.1  Bcast:172.16.255.255  Mask:255.255.0.0
          inet6 addr: fe80::10:18ff:fe00:1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:680 (680.0 B)

root@Edge1-A:/home/tim/OpenNSL/examples# exit
exit

drivshell>knetctrl netif show
Interface ID 1: name=swp1 type=Port vlan=0 port=xe0

drivshell>knetctrl filter show
Filter ID 1: prio=0 dest=NetIF(1) desc='' striptag ingport=xe0

drivshell>shell
root@Edge1-A:/home/tim/OpenNSL/examples# ping 172.16.0.4
PING 172.16.0.4 (172.16.0.4) 56(84) bytes of data.
From 172.16.0.1 icmp_seq=1 Destination Host Unreachable
From 172.16.0.1 icmp_seq=2 Destination Host Unreachable
From 172.16.0.1 icmp_seq=3 Destination Host Unreachable
^C
--- 172.16.0.4 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3015ms
pipe 3
root@Edge1-A:/home/tim/OpenNSL/examples# ping 172.16.0.3
PING 172.16.0.3 (172.16.0.3) 56(84) bytes of data.
From 172.16.0.1 icmp_seq=1 Destination Host Unreachable
From 172.16.0.1 icmp_seq=2 Destination Host Unreachable
From 172.16.0.1 icmp_seq=3 Destination Host Unreachable
^C
--- 172.16.0.3 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3006ms
pipe 3
root@Edge1-A:/home/tim/OpenNSL/examples# ping 172.16.0.2
PING 172.16.0.2 (172.16.0.2) 56(84) bytes of data.
From 172.16.0.1 icmp_seq=1 Destination Host Unreachable
From 172.16.0.1 icmp_seq=2 Destination Host Unreachable
From 172.16.0.1 icmp_seq=3 Destination Host Unreachable
^C
--- 172.16.0.2 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2999ms
pipe 3
root@Edge1-A:/home/tim/OpenNSL/examples# ifconfig
eth0      Link encap:Ethernet  HWaddr 80:1f:02:d6:3b:2b  
          inet addr:10.1.10.2  Bcast:10.1.255.255  Mask:255.255.0.0
          inet6 addr: fe80::821f:2ff:fed6:3b2b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:142907 errors:0 dropped:0 overruns:0 frame:0
          TX packets:54892 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:158018103 (158.0 MB)  TX bytes:4984852 (4.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:43 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:4816 (4.8 KB)  TX bytes:4816 (4.8 KB)

swp1      Link encap:Ethernet  HWaddr 02:10:18:00:00:01  
          inet addr:172.16.0.1  Bcast:172.16.255.255  Mask:255.255.0.0
          inet6 addr: fe80::10:18ff:fe00:1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:26 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1832 (1.8 KB)

root@Edge1-A:/home/tim/OpenNSL/examples# cat /proc/bcm/knet/dstats
Device debug stats (unit 0):
  Tx drop no skb               0
  Tx drop rcpu encap           0
  Tx drop rcpu sig             0
  Tx drop rcpu meta            0
  Tx drop pad failed           0
  Tx drop no resource          0
  Tx drop callback             0
  Tx drop no link              0
  Tx drop oversized            0
  Tx suspends                  0
  Rx0 filter to api            0
  Rx0 filter to netif          0
  Rx0 mirror to api            0
  Rx0 mirror to netif          0
  Rx0 drop no skb              0
  Rx0 drop no match            0
  Rx0 drop unkn netif          0
  Rx0 drop unkn dest           0
  Rx0 drop callback            0
  Rx0 drop no link             0
  Rx0 sync error               0
  Rx0 sync retry               0
  Rx0 sync maxloop             0
  Rx0 drop no buffer           0
  Rx1 filter to api            0
  Rx1 filter to netif          0
  Rx1 mirror to api            0
  Rx1 mirror to netif          0
  Rx1 drop no skb              0
  Rx1 drop no match            0
  Rx1 drop unkn netif          0
  Rx1 drop unkn dest           0
  Rx1 drop callback            0
  Rx1 drop no link             0
  Rx1 sync error               0
  Rx1 sync retry               0
  Rx1 sync maxloop             0
  Rx1 drop no buffer           0
  Rx2 filter to api            0
  Rx2 filter to netif          0
  Rx2 mirror to api            0
  Rx2 mirror to netif          0
  Rx2 drop no skb              0
  Rx2 drop no match            0
  Rx2 drop unkn netif          0
  Rx2 drop unkn dest           0
  Rx2 drop callback            0
  Rx2 drop no link             0
  Rx2 sync error               0
  Rx2 sync retry               0
  Rx2 sync maxloop             0
  Rx2 drop no buffer           0
root@Edge1-A:/home/tim/OpenNSL/examples# cat /proc/bcm/knet/stats
Device stats (unit 0):
  Tx packets          73
  Rx0 packets          0
  Rx1 packets          0
  Rx2 packets          0
  Rx0 pkts/intr        0
  Rx1 pkts/intr        0
  Rx2 pkts/intr        0
  Interrupts          73
  Timer runs           0
  NAPI reruns          0
  Filter 1 stats:
    Hits               0
root@Edge1-A:/home/tim/OpenNSL/examples# cat /proc/bcm/knet/dma
Pending events: 0x0
Tx DCB info (unit 0):
  api:   0
  dirty: 9
  cur:   9
  free:  32
  pause: no
  DCB  0: 0x7d4c4000 0x00080040 ... 0x00000000
  DCB  1: 0x7d502000 0x00080040 ... 0x00000000
  DCB  2: 0x7d533000 0x00080040 ... 0x00000000
  DCB  3: 0x7d54c000 0x00080040 ... 0x00000000
  DCB  4: 0x7d577000 0x00080040 ... 0x00000000
  DCB  5: 0x7d57e000 0x00080040 ... 0x00000000
  DCB  6: 0x7d599000 0x00080040 ... 0x00000000
  DCB  7: 0x7d5d3000 0x00080040 ... 0x00000000
  DCB  8: 0x7d5ff000 0x00080040 ... 0x00000000
  DCB  9: 0x7af52002 0x00080040 ... 0x00000000
  DCB 10: 0x7af53602 0x00080040 ... 0x00000000
  DCB 11: 0x7af53a02 0x00080040 ... 0x00000000
  DCB 12: 0x7d44c800 0x00080040 ... 0x00000000
  DCB 13: 0x7d44d000 0x00080040 ... 0x00000000
  DCB 14: 0x7d480000 0x00080040 ... 0x00000000
  DCB 15: 0x79ebe002 0x0008005e ... 0x00000000
  DCB 16: 0x79ebe002 0x0008005e ... 0x00000000
  DCB 17: 0x7c734000 0x00080052 ... 0x00000000
  DCB 18: 0x79ebe002 0x0008005e ... 0x00000000
  DCB 19: 0x7c741000 0x0008004a ... 0x00000000
  DCB 20: 0x79ebe002 0x0008005e ... 0x00000000
  DCB 21: 0x7c7b9000 0x0008004a ... 0x00000000
  DCB 22: 0x7c852000 0x0008004a ... 0x00000000
  DCB 23: 0x7d475000 0x00080040 ... 0x00000000
  DCB 24: 0x7d476000 0x00080040 ... 0x00000000
  DCB 25: 0x7d476800 0x00080040 ... 0x00000000
  DCB 26: 0x7d477000 0x00080040 ... 0x00000000
  DCB 27: 0x7d478800 0x00080040 ... 0x00000000
  DCB 28: 0x7d479800 0x00080040 ... 0x00000000
  DCB 29: 0x7d47a800 0x00080040 ... 0x00000000
  DCB 30: 0x7d48c000 0x00080040 ... 0x00000000
  DCB 31: 0x7d49f000 0x00080040 ... 0x00000000
Rx0 DCB info (unit 0):
  api:   0
  dirty: 0
  cur:   0
  free:  0
  run:   0
Rx1 DCB info (unit 0):
  api:   0
  dirty: 0
  cur:   0
  free:  0
  run:   0
Rx2 DCB info (unit 0):
  api:   0
  dirty: 0
  cur:   0
  free:  0
  run:   0
root@Edge1-A:/home/tim/OpenNSL/examples# cat /proc/bcm/knet/rate
Rate control (unit 0):
  Rx0 max rate    100000
  Rx0 max burst    10000
  Rx0 rate             0
  Rx0 tokens       10000
  Rx1 max rate    100000
  Rx1 max burst    10000
  Rx1 rate             0
  Rx1 tokens       10000
  Rx2 max rate    100000
  Rx2 max burst    10000
  Rx2 rate             0
  Rx2 tokens       10000
```

**Comment by hydratim** [comment]
This time built on 4.4.0-31-generic #50~14.04.1-Ubuntu SMP x86_64 GNU/Linux.

I've still not been able to find a matching kernel that will allow the import of the binary modules.

Thanks,
Tim

**Comment by simonknee** [comment]
This is the kernel we used on the AS5712 system:

root@ops-as5712:~# uname -a
Linux ops-as5712 3.9.11 #1 SMP Sun Aug 23 14:09:35 CST 2015 x86_64 GNU/Linux

**Comment by hydratim** [comment]
Ahh the openswitch kernel, I'll test that one then. Thanks.

**Comment by Lewis-Kang** [comment]
Hi,

If you want to use OpenNSL on the latest ONL, you have to build OpenNSL kernel modules using ONL's kernel header files which are version 3.16.39.

If you are not building OpenNSL binaries by yourself, you may contact with Edge-Core to get their release OpenNSL binaries for Edge-Core switches.

For OPX, the following is what I got, FYI.
admin@OPX:~$ uname -a
Linux OPX 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

**Comment by hydratim** [comment]
I am aware of that and have been doing so.

So far I've tried ONL, Ubuntu, OPS, a scratch build, none of which have worked with KNET on any of the eight EdgeCore AS5712-54X units I purchased for this deployment.

If you have a validated config (OS + OpenNSL build) with working KNET at EdgeCore please send it to me.

**Comment by Lewis-Kang** [comment]
Tim, do you expect ping to work? Whether ASIC is set to trap the related ARP and ICMP packets to CPU port?

**Comment by hydratim** [comment]
I would expect that ARP and ICMP is piped through to the CPU yes, otherwise I'd have to re-implement ARP in software, so that basic communication will work correctly.

**Comment by hydratim** [comment]
Seriously, NDA request declined and no response by e-mail? I'm seriously considering working with Mellanox on the spectrum platform instead at this rate.

**Comment by simonknee** [comment]
Hi Tim.  Sorry, I completely missed that you had a question for me last week.  I will confirm that we did do KNET testing on the release, and any other pointers I can provide.  You are using the example_knet app, correct?  I am presuming this is the "no response by e-mail" you were talking about, if not then let me know what else is pending.
As for the NDA, I am not in the loop for that and so cannot comment.  Follow up with me via email if you have questions.

**Comment by hydratim** [comment]
NDA has now been received signed, cross signed and returned so if I can get full access to the sourcecode then I'll be able to proceed with testing.
Since my last message I have managed to get a version of OpenSwitch that appears to be operating somewhat as expected, but they have pulled support for everything but the dell S6000-ON, and aren't responding, so I'm not sure how they have gotten it working as yet.

Yes, I was using both the example app and the code I'd written myself after following the relevant documentation. I'm beginning to suspect that it is just that the example_knet is broken (my code was heavily based on the example as the documentation was not clear otherwise).

As soon as I've got source access to the library I'll continue my work on our Switch OS (and thus OpenNSL and my opensource projects built on it).

Best,
Tim.

**Comment by hydratim** [comment]
I'll be picking this up again in about a month or two as I have other things I need to get done first, but essentially I think that it might just be shitty documentation and that the example_knet is wrong / broken.
I've got a working version of OpenSwitch where (provided I use the OpenSwitch interface) it sort of works. I'd like to keep this ticket open though for now, until I've fixed the example_knet and submitted the pull request.

**Comment by pwariche** [comment]
Having the same issue, compiling the sdk against ONL kernel 3.16.39-OpenNetworkLinux and example_knet does not send icmp reply back to the CPU.

**Comment by simonknee** [comment]
We did not test OpenNSL or any of its example applications against the 3.16.39-OpenNetworkingLinux kernel, we used the OpenSwitch kernel instead.  Looks like there are real problems with 3.16.39 and OpenNSL.  We will take a look and see if we can replicate it at Broadcom.

**Comment by hydratim** [comment]
Hi Simon, 

I'm still waiting on my SLA so that I can assist to the fullest of my ability.

I would strongly recommend focussing exclusively on kernels > 4.8.x now due to some rather serious security issues in all preceding releases and the patches not being backwards compatible.

-Tim.

**Comment by simonknee** [comment]
Understood Tim, and I know the SLA process can take a while.  To be honest we have been focused on other dev items too, but now we have some resources who can take a look at this.  For now we will focus on the stock ONL distro since multiple people have reported issues there.

**Comment by hydratim** [comment]
Hi Simon,

While I am pretty sure I can work around the issue on my platform, I would greatly appreciate it if you'd double check that the example_knet code works correctly too (not just via the debug shell). I suspect that the example code is not quite right.

Thanks,
Tim.

**Comment by simonknee** [comment]
Agreed.  Goal is to make sure example_knet works with the current ODL.

**Comment by simonknee** [comment]
Tim, Patrick,

We did discover some issues with the 3.3.0.2 version of example_knet - you were right, it was broken as is..  The example_knet.c from 3.3.0.3 has the fixes in it (already published to github).  These might not be the only problems since we are still testing example_knet on the later kernel you are using.

I suggest you retry with OpenNSL 3.3.0.3 while we continue our testing with the later kernel.

Note, if you are using the ONIE installer build from openswitch then it runs switchdrvr at power up, so you need to take some steps after it boots before you run example_knet:

1) Stop openswitch switchdrvr instance
systemctl status | grep switchd
systemctl status switchd.service
systemctl stop switchd
systemctl stop ops-pmd

2) Run the following commands to enable laser on AS5712 ports
i2cset -y 1 0x61 0x0c 0x00 b
i2cset -y 1 0x61 0x0d 0x00 b
i2cset -y 1 0x61 0x0e 0x00 b

i2cset -y 1 0x62 0x0c 0x00 b
i2cset -y 1 0x62 0x0d 0x00 b
i2cset -y 1 0x62 0x0e 0x00 b

3) Run the following commands to run OpenNSL sample application:
rmmod linux-user-bde
rmmod linux-bcm-knet
rmmod linux-kernel-bde

rm -f /dev/linux-kernel-bde
rm -f /dev/linux-user-bde
rm -f /dev/linux-bcm-knet

mknod /dev/linux-kernel-bde c 127 0
mknod /dev/linux-user-bde c 126 0
mknod /dev/linux-bcm-knet c 122 0

insmod linux-kernel-bde.ko
insmod linux-user-bde.ko
insmod linux-bcm-knet.ko

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
export OPENNSL_CONFIG_FILE=config.as5712

4) Run example_knet

**Comment by hydratim** [comment]
Hi Simon,

Great! Good timing too, I was about to start asking for an update, I'll begin testing tomorrow.
Also I've got all the legal stuff out the way now (NDA & SLA all signed by both sides), where can I get access to the library source.

-Tim

**Comment by hydratim** [comment]
Sorry it took me a while to validate this. The pre-compiled example works, I haven't checked the source works yet.

**Comment by hydratim** [comment]
I have checked the source, updated my opennsl-man draft and confirmed it as working.
There is still some information (such as connection state / speed data) that is not getting through to the kernel, but essentially it is working, so I'm closing the issue.

**Comment by Blueblazer172** [comment]
Is there even support for an AS5610-52X? I can't find any hints this device is supported by opennsl...
