### ISSUE TITLE
OpenNSL v3.3.0.2 L2 multicast

### ISSUE THREAD

**Issue by lostdistance** [Broadcom-Switch/OpenNSL#17]
Hi,

I am using OpenNSL v3.3.0.2 on an Accton AS5812-54X (BCM56864 Trident-II+) switch. My aim is to enable L2 multicast, such that packets whose destination MAC is in the range 01-00-5E-00-00-00 to 01-00-5E-7F-FF-FF are replicated on the required output ports.

Using the example_vxlan.c program as a guide, I was able to create/destroy multicast groups with opennsl_multicast_create/destroy, and add/delete ports with opennsl_multicast_egress_add/delete.

My problem is that I can find no obvious method of assigning an L2 multicast address to a multicast group.

Looking at the examples in the subsequent OpenNSL v3.3.0.3, an "l2mc_group" field was added to the opennsl_l2_addr_t structure, and this does seem to offer an answer. Unfortunately this field is absent from OpenNSL v3.3.0.2.

Is anyone able to offer guidance or example software for OpenNSL v3.3.0.2 L2 multicast?

Best regards.

**Comment by santoshdoke** [comment]
Hi,

Your analysis is correct. We need 'l2mc_group' field to link the L2 address to the multicast group.  The latest release is 3.4.x. Can you move to the latest version?

For example:

flags = OPENNSL_MULTICAST_TYPE_L2;
rv = opennsl_mutlicast_create(unit, flags, &l2mc_group);

l2addr.l2mc_group = l2mc_group;
/* Set other fields in l2addr like MAC and VLAN */
rv = opennsl_l2_addr_add(unit, &l2addr);

Thanks

**Comment by lostdistance** [comment]
Thank you very much for the response; I'll approach Edgecore for a more recent version of OpenNSL.

**Comment by lostdistance** [comment]
I have received word that Edgecore do not have newer version than v3.3.0.2 at the moment.

**Comment by simonknee** [comment]
Accton/Edgecore should now have access to 3.1.4.5.

**Comment by simonknee** [comment]
Sorry, I should have said Accton/Edgecore now have access to 3.4.1.5.

**Comment by lostdistance** [comment]
Today I received word that Edgecore plan to provide OpenNSL 3.4.1.5 on the AS5812-54X before the end of November. Evidently they still have work to do on it.
