### ISSUE TITLE
bcm modules creation .ko for kernel >3.10 

### ISSUE THREAD

**Issue by sri1983n** [Broadcom-Switch/OpenNSL#2]
sdk-x.y.z-gpl-modules/systems/linux/user/common/Makefile 
does not support building modules for latest kernel (.ko modules). With below code

ifeq ($(kernel_version),2_6)
KOBJ=ko
else
KOBJ=o
endif

Currently it builds .ko modules only for 2_6. We should have it built for any kernels greater than or equal  2.6 

-Sri

**Comment by simonknee** [comment]
Hi Sri,

Could you try exporting the following variable before issuing make in the platform specific folder:

export LINUX_UAPI_SPLIT=1
cd sdk-6.4.6-gpl-modules/systems/linux/user/x86-smp_generic_64-2_6/
make

Regards,

Simon.

**Comment by srideepd** [comment]
thanks simon that work. forgot to update.
