### ISSUE TITLE
3.4.1.5 ofdpa support dropped?

### ISSUE THREAD

**Issue by vitalivanov** [Broadcom-Switch/OpenNSL#25]
Hello Broadcom team,

OF-DPA support is dropped in latest release:

--- include/opennsl/ofdpa_api.h
--- include/opennsl/ofdpa_datatypes.h

Does it mean that OF-DPA is obsolete?

What to do with applications like OpenSwitch that uses OF-DPA functionality thru OpenNSL?

Thanks,
Vitaliy

**Comment by simonknee** [comment]
Hi Vitaliy,

You are correct, OF-DPA support has been dropped in OpenNSL 3.4.  The legacy (HPE) OpenSwitch code will need to be updated to remove OF-DPA support, or you could continue to use an older version of OpenNSL with OPS.

Simon.

**Comment by vitalivanov** [comment]
Thanks for comments @simonknee.
