### ISSUE TITLE
OpenNSL initialization problem on as5912 (Qumran chipset 88370)

### ISSUE THREAD

**Issue by mlabbaf** [Broadcom-Switch/OpenNSL#28]
I work on the Edge-core AS5912 board that use Qumran 88370 chipset, and I want to use OpenNSL to develop my application.
I run the ONL operating system (linux kernel 3.16.53)  and I compile the linux-user-bde.ko and linux-kernel-bde.ko modules. I copy the libopennsl.so from Agema 7648A board that I downloaded from the following link:
https://github.com/Broadcom-Switch/OpenNSL/tree/master/bin/ag-x86-dnx-deb80

root@localhost:~# uname -a 
Linux localhost 3.16.53-OpenNetworkLinux #1 SMP Sun Feb 25 15:10:25 UTC 2018 x86_64 GNU/Linux

However, I cannot initialize the OpenNSL and I get the error after calling "opennsl_driver_init((opennsl_init_t *) NULL)" api. I got the following error:

result:
Initializing the system.
Platform configuration file "/mnt/onl/data/nfs/config" is used
Platform Boot flags: 0x0
DMA pool size: 16777216
PCI unit 0: Dev 0x8370, Rev 0x11, Chip BCM88370_B0, Driver BCM88370_B0

Initializing platform

Error initializing platform, rc = -1.

Error initializing driver, rc = -1.

Failed to initialize the system. Error (-11) Operation failed

Also, I use the default configuration and I get the similar error.
How I can solve the problem?

Thanks in advance

**Comment by lostdistance** [comment]
Hi,

You should contact your Edgecore distributor or Edgecore support. They can provide you with an OpenNSL release for Edgecore switches.

The most recent release I received from Edgecore is OpenNSL 3.4.1.5 which supports the following switches:

AS4600-54T
AS4610-30P
AS4610-30T
AS4610-54P
AS4610-54T
AS5710-54X
AS5712-54X
AS5812-54T
AS5812-54X
AS5912-54X
AS6712-32X
AS6812-32X
AS7312-54X
AS7712-32X
AS7716-32X

Best regards.

**Comment by mlabbaf** [comment]
Thanks for your reply, 

We will contact Edge-core to get the OpenNSL files.
However, I downloaded the OpenNSL (with tag 3.5.0.1) which is newer than 3.4.1.5
Our problem is just related to the OpenNSL config file, or we should change other files like: libopennsl.so and ... ?

Thanks

**Comment by lostdistance** [comment]
Hi,

I do not know what your exact problem is. Certainly the Agema AGC7648A is from a different manufacturer, so I would not expect its libopennsl.so to work with an Edgecore AS5912.

Best regards.

**Comment by mlabbaf** [comment]
I thought that the libopennsl.so is only depends on the broadcom chipset family and cpu architecture (X86, ARM, MIPS and ...). As I know, both AGC7648A and AS5912 use Qumran-MX and Intel Rangeley C2538. 
However, it seems that each board requires specific libopennsl.so !

Is there any plan to integrate linux-kernel-bed.ko, linux-user-bed.ko and libopennsl.so to the ONL?

**Comment by lostdistance** [comment]
Hi,

The OpenNSL Release Notes Section 3 lists the supported platforms for that release. If a platform is not listed then presumably developers need to refer to the manufacturer's documentation and support.

In my case I did verify that OpenNSL support was provided by the manufacturer before purchasing my AS5812-54X switch, since that switch was not listed in the Release Notes.

I agree that the distinction between the software released here and the software provided by the manufacturers could be more clearly explained.

Best regards.

**Comment by mlabbaf** [comment]
Thanks for your replies,
I think the problem is solved, now.
Beside this topic, I'm curious to know is it possible to set log level in OpenNSL library that give us more information about the underlying events?

**Comment by simonknee** [comment]
I checked with the dev team, unfortunately it is not possible at this point to set an increased log level.

**Comment by kiyoTokyo** [comment]
> Hi,
> 
> You should contact your Edgecore distributor or Edgecore support. They can provide you with an OpenNSL release for Edgecore switches.
> 
> The most recent release I received from Edgecore is OpenNSL 3.4.1.5 which supports the following switches:
> 
> AS4600-54T AS4610-30P AS4610-30T AS4610-54P AS4610-54T AS5710-54X AS5712-54X AS5812-54T AS5812-54X AS5912-54X AS6712-32X AS6812-32X AS7312-54X AS7712-32X AS7716-32X
> 
> Best regards.

Hello,

Edgecore support no longer provides files.

So I am looking for files such as 'opennsl-accton_3.5.0.3+accton5.0-1_amd64.deb'.

If you still have these files, could you please share them?
