### ISSUE TITLE
Error logs shown after initialization of device.

### ISSUE THREAD

**Issue by JunhoSuh** [Broadcom-Switch/OpenNSL#3]
Hi all~

I am currently testing OpenNSL APIs for my forwarding application on Wedge platform.
But, after device initialization with opennsl_device_init(), some error logs are shown even though the initialization is done successful. The error logs are shown as below:

[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]STATUS: 0x00000403
[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]OPCODE: 0x05000000
[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]START ADDR: 0x000001
0f
[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]CUR ADDR: 0xdfe316a0
[socdmadesc.0]0:_soc_sbusdma_desc: [socdmadesc.0]IP COUNTERS failed(ERR)
[socdmadesc.0]0:_soc_sbusdma_error_details: [socdmadesc.0]Error while reading de
scriptor from host memory.
[socdmadesc.0]0:_soc_sbusdma_port_ctr_cb: [socdmadesc.0]Counter SBUSDMA failed:
Handle:1 port:0.

[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]STATUS: 0x00000403
[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]OPCODE: 0x00000001
[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]START ADDR: 0xdfe316
bc
[socdmadesc.0]0:_soc_sbusdma_curr_op_details: [socdmadesc.0]CUR ADDR: 0x00000000
[socdmadesc.0]0:_soc_sbusdma_desc: [socdmadesc.0]EP COUNTERS failed(ERR)
[socdmadesc.0]0:_soc_sbusdma_error_details: [socdmadesc.0]Error while reading de
scriptor from host memory.
[socdmadesc.0]0:_soc_sbusdma_port_ctr_cb: [socdmadesc.0]Counter SBUSDMA failed:
Handle:2 port:0.
...

My guess is I didn’t set up for all ports yet. Someone can help me?

Thanks~

**Comment by simonknee** [comment]
Junho, did you make progress with this?

**Comment by JunhoSuh** [comment]
I close this issue.
