### ISSUE TITLE
netserve can’t be executable

### ISSUE THREAD

**Issue by JunhoSuh** [Broadcom-Switch/OpenNSL#4]
Hi,

The binary of netserve for each platform is not executable. I don’t know why?

Thanks~

**Comment by simonknee** [comment]
Hi Junho,

I did a new clone of the OpenNSL repo and in all cases the netserve file had the executable bit set.  Is there something I am missing?

Simon.

**Comment by JunhoSuh** [comment]
When I run the netserve, it shows -bash: ./netserve: No such file or directory

Junho

**Comment by simonknee** [comment]
I understand now, thanks Junho.  Typically you get the error you describe when you attempt to execute a binary on a OS different to that it was compiled on.  For example, trying to execute a 32-bit binary on a 64-bit system, or perhaps trying to execute a binary compiled for CentOS on Ubuntu.  Can you check that you base OS matches the netserve you are trying to use?

Simon.
