### ISSUE TITLE
Memory Leak, bcm-knet.c

### ISSUE THREAD

**Issue by davidsilveiro** [Broadcom-Switch/OpenNSL#5]
within **sdk-6.4.10-gpl-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c:5848**

**Comment by simonknee** [comment]
Hi David,

Line 5851 in that file is "return -EIO:'.  Perhaps you are referring to a different line, or may be we are missing the issue??

Simon.

**Comment by davidsilveiro** [comment]
Hey simon

Sorry for the vagueness dude

Basically cppcheck identified the pointer sinfo on line 5848 as being a memory leak, but categorized it at 5851 instead.

**Comment by simonknee** [comment]
Thanks David, I see what you mean now.  We will look into it and get back to you.

Simon.

**Comment by simonknee** [comment]
Hi David,

We looked into this further and do not believe it is a memory leak.  The reason is that the pointer assigned to sinfo by bkn_create_sinfo() is also added to the _sinfo_list global variable, and that list is free'ed as part of _cleanup().  Let us know if we are missing something.

Simon.
