### ISSUE TITLE
Support for an AS5610-52X ?

### ISSUE THREAD

**Issue by Blueblazer172** [Broadcom-Switch/OpenNSL#52]
Hi, i've been searching for a while now and I can't find any hints this device is supported by opennsl... Is there any way opennsl can be build by hand for the Trident+ Powerpc cpu on the AS5610-52X?

**Comment by ramanashok** [comment]
Hi,
Hi, I work at Broadcom  and  used to be the PM for OpenNSL. 
Please note OpenNSL is no longer supported by Broadcom. The OpenNSL team has moved on either from Broadcom or to other internal projects (including myself).
-Ashok

**Comment by Blueblazer172** [comment]
Hi Ashok,

thanks for the reply. Is it anyhow possible to get the old builds of opennsl (opennsl-accton....powerpc.deb files) that work with my old model? 

If not the switch is completely e-waste, cause it only runs cumulus and picos which are sooo expensive :/ 

Regards

**Comment by ramanashok** [comment]
Sorry, we have don't have this binary. I believe the 5610 platform is from Edgecore/Accton. Please check with them. 

In any case, openNSL is not a NOS. so your comparisons may not be valid. What NOS do you plan to run?

Sincerely,
Ashok

**Comment by Blueblazer172** [comment]
I've build ONL (Open Network Linux) with the current kernel and it boots correctly via ONIE, but no ports show up... I think OpenNSL is the driver between the switch asic and ONL. I'm searching for a simple Layer2 config even without vlans. I just need to ping and the port speed. Is there any way to get this running ?

**Comment by Blueblazer172** [comment]
Btw I would be happy with any NOS that has build-in drivers for the switch fabric

**Comment by Blueblazer172** [comment]
push

**Comment by Blueblazer172** [comment]
@rocksit I have tried nearly everything back in November 22. Not even simple layer 2 just for the Speed on the ports was working. ONL is a operating system for the baremetal switches. This is the only thing that is working right out of the box. But if you want simple ping or layer 2 switch config you also need a compatible driver for the switch asiic. Broadcom discontinued the Support for OpenNSL witch is/was the only compatible driver for the switch fabric. Since no one has the needed kernel mods for the powerpc cpu you wont be able to get anything working on the switch. I've tried cross compiling with c and the exact kernel version but it always failed with 1000x errors. You can have a look at this google group: https://groups.google.com/g/opennetworklinux/c/duHZ4MR-3RA/m/mqemadFSAQAJ

I've wasted 3-4 weeks trying to get L2 working on the switch and then sold both of them and bought two Mellanox SX1012. Worked right out of the box with gui and awasome cli. Baremetal switches is something i would never try again!
