### ISSUE TITLE
TOOLCHAIN

### ISSUE THREAD

**Issue by Voskrese** [Broadcom-Switch/OpenNSL#6]
где скачать TOOLCHAIN ?
https://github.com/Broadcom-Switch/OpenNSL/blob/master/bin/gto-trident-brl20/INSTALL
TOOLCHAIN_EXEC_PREFIX=$(WRLINUX_BASE)/wrlinux-3.0/layers/wrll-toolchain-4.3-85/powerpc/toolchain/x86-linux2

**Comment by simonknee** [comment]
That tool chain is available from Broadcom after a software license agreement is signed.  Reach out to your Broadcom contact for further information.

**Comment by liujun2001** [comment]
are openswitch project using the same toolchain as BRCM SDK? my understanding is that openswitch  build just pull out the *.ko file from this BRCM_SWITCH/OPENNSL, and linked into the image, is this correct?  Thanks in advance

**Comment by simonknee** [comment]
I don't believe they are using the exact same toolchain, and I doubt the .ko modules can be used as is.  Instead OPS create their own release of OpenNSL binaries that they publish on their archives - this has the full set of libraries and source code.  These are then pulled over and used as part of the OPS build.
