### ISSUE TITLE
Error message while initializing driver

### ISSUE THREAD

**Issue by JunhoSuh** [Broadcom-Switch/OpenNSL#7]
Hi,

I got this error while initializing the driver. I use the OpenNSL library (i.e., libopennsl.so.1) and driver modules (linux-*.ko) of CDP version (i.e., 3.1.0.9) against linux kernel 3.19.5 for wedge-trident.
I don’t know why this happened.

Here is error message I got.

Initializing OpenNSL Driver
Platform default configuration is used
Platform Boot flags: 0x0
mmap failed: : Invalid argument
ERROR: Assertion failed: (_dma_vbase = _mmap(_dma_pbase, _dma_size)) at /home/msiva/shiva/wedge/msiva-opennsl-dev_RELEASE_INT_OPENNSL_6.4_3.1.0.9/vobs/opennsl/sdk/systems/bde/linux/user/linux-user-bde.c:981
ERROR: Continue or quit (c/q)? [q] c
WARNING: Correct behavior no longer guaranteed
DMA pool size: 16777216
PCI unit 0: Dev 0xb850, Rev 0x03, Chip BCM56850_A2, Driver BCM56850_A0

Initializing platform
Device Configuration - SUCCESS!

interrupt priority set: : Operation not permitted
0:soc_attach: soc_attach: unit 0 failed
0:soc_schan_op: SOC_SCHAN_OP() function is undefined
sysconf_attach: bcm device init failed
ERROR: SOC unit 0 attach failed
Boot flags: Cold boot
Segmentation fault (core dumped)

Also, I put the script to insmod the kernel modules that I used.

options linux-kernel-bde maxpayload=128 dmasize=16M
options linux-bcm-knet base_dev_name=bdev use_rx_skb=1 num_rx_prio=10

Thanks~

**Comment by simonknee** [comment]
Hi Junho,

It looks like the kernel you are using might be different to the version the OpenNSL modules were compiled with (CentOS 6.5).  You could try compiling new modules from the sdk-6.4.10-gpl-modules- directory, or start with CentOS 6.5.

If you have the OpenNSL ODP release then you could try a full compile of the OpenNSL libraries on your platform setup.

Additional information is in bin/wedge/INSTALL.

We would also be interested to see the output from the following commands:

uname -a
lspci
ls -lrt /dev/
lsmod

Regards,

Simon.
